### ISSUE TITLE
Error since update to 25.09.2

### ISSUE THREAD

**Issue by MadPleasureShadowbringer** [jefdongus/insert-symbols-anki-addon#56]
Hi, recently updated to 25.09, and I would get error messages about the addon not working when booting anki. Here are the debug info:

Anki 25.09.2 (3890e12c) (ao)
Python 3.14.2 Qt 6.10.1 PyQt 6.10.2
Platform: Linux-6.18.5-2-cachyos-x86_64-with-glibc2.42

When loading Symbols As You Type:
Traceback (most recent call last):
  File "/usr/lib/python3.14/site-packages/aqt/addons.py", line 250, in loadAddons
    __import__(addon.dir_name)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/transreimu/.local/share/Anki2/addons21/2040501954/__init__.py", line 1, in <module>
    from . import insert_symbols
  File "/home/transreimu/.local/share/Anki2/addons21/2040501954/insert_symbols.py", line 19, in <module>
    from .symbol_window import SymbolWindow
  File "/home/transreimu/.local/share/Anki2/addons21/2040501954/symbol_window.py", line 20, in <module>
    PYQT_VER = get_pyqt_version()
  File "/home/transreimu/.local/share/Anki2/addons21/2040501954/get_version.py", line 64, in get_pyqt_version
    if pkgutil.find_loader('PyQt4'):
       ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'find_loader'
